export interface Currency {
    abbreviation: string
    display: string
}

export const currencies: Array<Currency> = [
    {abbreviation: 'usd', display: 'United States Dollar'},
    {abbreviation: 'aed', display: 'Arab Emirates dirham'},
    {abbreviation: 'ars', display: 'argentenian peso'},
    {abbreviation: 'aud', display: 'australian dollar'},
    {abbreviation: 'bdt', display: 'bangladesh teka'},
    {abbreviation: 'bhd', display: 'bahrain dinar'},
    {abbreviation: 'bmd', display: 'bermuda dollar'},
    {abbreviation: 'brl', display: 'brazilian real'},
    {abbreviation: 'cad', display: 'canadian dollar'},
    {abbreviation: 'chf', display: 'switzerland franc'},
    {abbreviation: 'clp', display: 'chilean peso'},
    {abbreviation: 'cny', display: 'China Yuan/Renmibi'},
    {abbreviation: 'czk', display: 'Czech Koruna'},
    {abbreviation: 'dkk', display: 'Denmark Krone'},
    {abbreviation: 'eur', display: 'Euro'},
    {abbreviation: 'gbp', display: 'Great Britan Pound'},
    {abbreviation: 'hkd', display: 'Hong Kong Dollar'},
    {abbreviation: 'huf', display: 'Hungary Forint'},
    {abbreviation: 'idr', display: 'Indonesia Rupiah'},
    {abbreviation: 'ils', display: 'Israel New Shekel '},
    {abbreviation: 'inr', display: 'India Rupee '},
    {abbreviation: 'jpy', display: 'Japan Yen'},
    {abbreviation: 'krw', display: 'South Korea Won '},
    {abbreviation: 'kwd', display: 'Kuwait Dinar '},
    {abbreviation: 'lkr', display: 'Sri Lanka Rupee '},
    {abbreviation: 'mmk', display: 'Myanmar Kyat '},
    {abbreviation: 'mxn', display: 'Mexico Peso'},
    {abbreviation: 'myr', display: 'Malaysia Ringgit '},
    {abbreviation: 'ngn', display: 'Nigeria Naira '},
    {abbreviation: 'nok', display: 'Norway Kroner '},
    {abbreviation: 'nzd', display: 'New Zealand Dollar '},
    {abbreviation: 'php', display: 'Philippines Peso '},
    {abbreviation: 'pkr', display: 'Pakistan Rupee '},
    {abbreviation: 'pln', display: 'Poland Zloty '},
    {abbreviation: 'rub', display: 'Russia Rouble '},
    {abbreviation: 'sar', display: 'Saudi Arabia Riyal '},
    {abbreviation: 'sek', display: 'Sweden Krona '},
    {abbreviation: 'sgd', display: 'Singapore Dollar '},
    {abbreviation: 'thb', display: 'Thailand Baht '},
    {abbreviation: 'try', display: 'Turkish New Lira '},
    {abbreviation: 'twd', display: 'Taiwan Dollar '},
    {abbreviation: 'uah', display: ' Ukraine Hryvnia '},
    {abbreviation: 'vef', display: 'Venezuelan Bolivar'},
    {abbreviation: 'vnd', display: 'Vietnam Dong'},
    {abbreviation: 'zar', display: 'South Africa Rand '},
    {abbreviation: 'xag', display: 'Gold'},
    {abbreviation: 'xau', display: 'Silver'}
]